---
- name: Converge
  hosts: all
  gather_timeout: 300

  vars:
    shoutcast_streams:
      - port: 8000
        listeners: 10
        passwd: 4W7APeAAv7w7jUt
        admin_passwd: y48DCnuE74RRSYVAWBjpWzXbL7brhe
        state: present

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: sparknsh.shoutcast
