---

- name: Converge
  hosts: all
  gather_timeout: 300

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: sparknsh.%ANSIBLE_GALAXY%
